### DISCUSSION TITLE
Where to add custom styles?

### DISCUSSION THREAD

**Discussion by RichardUUU** [Zavy86/WikiDocs#243] [General]
I'm using a docker version (unRaid). My folder structure looks like: `appdata\wikidocs\documents\homepage`
Where would I put styles/styles-custom.css?

**Comment by leomoon** [comment]
I'm not sure but based on the docker configuration I see on the `README.md`, we're not exposing styles folder:
```
services:
  wikidocs:
    image: zavy86/wikidocs
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 80:80
    volumes:
      - /path/to/local/wikidocs/datasets/or/volume:/datasets
```

You would need to also expose: `- /path/to/local/wikidocs/datasets/or/volume:/styles`

But I'm not sure if it would copy the already existing styles.

**Comment by RichardUUU** [comment]
Thanks. I don't know if it makes a difference that https://www.wikidocs.app/customization says: 
`You can customize the default template by creating the file styles/styles-custom.css.`
I would infer that styles-custom.css would override the existing styles.
Regardless, I have mapped /styles to an outside directory. It didn't copy the existing styles. And styles-custom.css does not seem to override existing styles. 
![image](https://github.com/user-attachments/assets/f976bd86-3a37-4596-9f5a-e07a7d62e819)

styles-custom.css
```
h2,
.h2 {
  font-size: 2rem;
  margin: 1.5rem 0 1rem 0;
  color: yellow;
}

```

**Comment by leomoon** [comment]
there's no custom style by default. that's only when you wanna customize.

I've used the custom style but I had manual install of wikidocs.

**Reply by RichardUUU** [reply]
> there's no custom style by default. that's only when you wanna customize.

I'm not sure how that differs from what I tried to say. I want to add the custom-styles.css file so it will customize. I only mentioned copying the existing styles because you mentioned it earlier.

Thanks, for responding. Considering that custom-styles.css is in the docs, hopefully someone will be able to elucidate on how it works.

**Comment by leomoon** [comment]
My previous message was to tell you that custom style works with manual setup!

Custom style is not in datasets or documents.

It is at the root of the wikidocs setup. Exposing it didn't work. We might need to create a new image to make that work with docker.

**Reply by Zavy86** [reply]
ok I'll try to work on in it the next week

**Comment by leomoon** [comment]
Actually now that i think about it, we can expose the actual file instead of the whole folder. 
```
services:
  wikidocs:
    image: zavy86/wikidocs
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 80:80
    volumes:
      - path/to/local/wikidocs/datasets:/datasets
      - path/to/local/wikidocs/styles/styles-custom.css:/styles/styles-custom.css
 ```
Then create that css file before running docker compose.
