### ISSUE TITLE
"Long" wiki name gets cut off instead of some form of scaling.

### ISSUE THREAD

**Issue by Wabuo** [Zavy86/WikiDocs#100]
### Describe your issue

I changed the Wiki name to `Village|Wiki`.
And now the last `i` gets cut off -- Brave browser

And in Firefox, the name gets split in half and put on a new line.

I would prefer if the font would just shrink to make it fit, up to a certain point before the line break happens and I guess that cut off is just a misbehaving browser.

PS: cheers for this awesome "little" piece of software.

### Device and settings

official docker

### Steps to reproduce

Change the wiki name to `Village|Wiki`

open the wiki in Brave, enjoy your new `Village|Wik`

### Screenshots (optional)

Brave
![Screenshot from 2024-02-01 00-34-32](https://github.com/Zavy86/WikiDocs/assets/6383080/a4a608ca-34f7-4a27-83fd-4687449e0e77)

Firefox
![Screenshot from 2024-02-01 00-34-48](https://github.com/Zavy86/WikiDocs/assets/6383080/e7a11e18-07fb-4c9b-80c7-5aa57e4234c6)

### Extra fields

- [ ] I'd like to work on this issue

**Comment by Wabuo** [comment]
I guess this can be ignored!

As soon as I filled the Main Page with some contend, it seems to work as expected.

I'll keep this open for now and see will close it by tomorrow if it's really only an issue while the main page is "empty"

**Comment by giufus** [comment]
Interesting project @Zavy86 

@Wabuo It can't be considered a fix, is a customisation and customisations are git-ignored.
Add a custom style like this. 

1. Locate the Custom CSS File: Find or create the styles/styles-custom.css file in your WikiDocs installation.   
This ensures your changes won't be overwritten by future updates.

2. Add the Following CSS Rule: 
```css
/* Prevent title wrapping and add ellipsis if it overflows */
#logo-container h1 {
    white-space: nowrap;     /* Prevent the text from wrapping to a new line */
    overflow: hidden;        /* Hide the part of the text that overflows */
    text-overflow: ellipsis; /* Show an ellipsis (...) to indicate hidden text */
    
    /* Optional: You might slightly reduce the default size to give more room */
    /* Experiment with values like 3.2rem or 3rem if needed */
    font-size: 3.2rem;
}



```
