### ISSUE TITLE
No links in left sidebar to navigate

### ISSUE THREAD

**Issue by Anilo1990** [Zavy86/WikiDocs#123]
### Describe your issue

With my WikiDocs deployment running in Docker, no links to the chapters in WikiDocs are created.

This is my docker compose

```
version: '3'

services:
  wikidocs:
    image: zavy86/wikidocs
    container_name: wikidocs
    environment:
      - PUID=1026
      - PGID=100
    ports:
      - 61828:80
    volumes:
      - /data/compose/wikidocs/:/datasets
```

### Device and settings

Raspberry Pi, Portainer 2.19.5, Docker

### Steps to reproduce

Adding a new document to WikiDocs
Adding a new document to WikiDocs with content
Adding new Headings

### Screenshots (optional)

![grafik](https://github.com/Zavy86/WikiDocs/assets/16625964/4f22d49d-ed19-4f0c-a4d6-8abbf4a5cd5a)

### Extra fields

- [ ] I'd like to work on this issue
